# Generated by Django 4.0.4 on 2022-05-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Random_Legends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='legend_class',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='legend',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='legend',
            name='name',
            field=models.CharField(default='0', max_length=25),
        ),
    ]
