# Generated by Django 4.0.4 on 2022-05-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Random_Legends', '0002_legend_legend_class_alter_legend_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legend',
            name='id',
        ),
        migrations.AlterField(
            model_name='legend',
            name='name',
            field=models.CharField(default='0', max_length=25, primary_key=True, serialize=False),
        ),
    ]
